# Generated by Django 4.2.3 on 2023-07-10 21:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisitedPlace',
            new_name='Visited',
        ),
    ]
