# Generated by Django 4.2.3 on 2023-07-13 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_rename_visited_visitedplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitedplace',
            name='date_visited',
        ),
    ]
