# Generated by Django 4.2.3 on 2023-07-13 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('location', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2)])),
                ('post_information', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
