# Generated by Django 4.2.3 on 2023-07-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_post_posted_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.URLField(max_length=300),
        ),
    ]
