# Generated by Django 4.2.3 on 2023-07-16 11:16

import FinalProject.destinations.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dreamdestination',
            name='location',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), FinalProject.destinations.validators.validate_location]),
        ),
    ]
